import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/layouts/(admin)/Sidebar";
import AuthProvider from "@/Providers/AuthProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <div className="flex flex-row bg-primary min-h-screen">
            <div className="w-[15%] h-full">
              <Sidebar />
            </div>
            <div className="w-[85%] py-6 pr-6">
              <div className="bg-admin rounded-[30px] p-6 min-h-[94vh]">
                {children}
              </div>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
